export const blogCategories = [
    "Technology",
    "Business",
    "Finance",
    "Health & Wellness",
    "Lifestyle",
    "Travel",
    "Food & Drink",
    "Education",
    "Science",
    "Environment",
    "Fashion & Beauty",
    "Entertainment",
    "Sports",
    "Politics",
    "Art & Culture",
    "Parenting",
    "Personal Development",
    "DIY & Home Improvement",
    "Real Estate",
    "Marketing",
    "Productivity",
    "Relationships",
    "Spirituality",
    "Automotive",
    "Gaming",
    "History",
    "Photography",
    "Startups",
    "Freelancing",
    "Career Advice",
    "Finance & Investing",
    "Pet Care",
    "Books & Literature"
  ];
  