import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const kubSansThin = localFont({
  src: "./fonts/KumbhSans-Light.ttf",
  variable: "--font-kubsans-thin",
  weight: "100 300",
});
const kubSansRegular = localFont({
  src: "./fonts/KumbhSans-Regular.ttf",
  variable: "--font-kubsans-regular",
  weight: "400 700",
});
const kubSansMedium = localFont({
  src: "./fonts/KumbhSans-Medium.ttf",
  variable: "--font-kubsans-medium",
  weight: "500 600",
});
const kubSansBold = localFont({
  src: "./fonts/KumbhSans-Bold.ttf",
  variable: "--font-kubsans-bold",
  weight: "800 900",
});

export const metadata: Metadata = {
  title: "Lymdata blog | Appp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicons/favicon-16x16.png" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kubSansThin.variable} ${kubSansRegular.variable} ${kubSansMedium.variable} ${kubSansBold.variable} antialiased`}
      >
        {children}
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
         
        >
          {children}
        </ThemeProvider> */}
      </body>
    </html>
  );
}
